/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Incremental raw LZMA2 compressor (dictionary pinned out of band, A10). */
export declare class Lzma2Compressor {
  /**
   * Create a streaming compressor. `options` is optional; an absent or
   * empty object uses [`DEFAULT_PRESET`].
   *
   * The `preset` (and, for LZMA2, `dictSize`) are validated before the
   * native encoder is built, so out-of-range input rejects with an
   * `InvalidArg` error instead of panicking or OOM-ing the process.
   */
  constructor(options?: Lzma2CompressorOptions | undefined | null)
  /**
   * Feed one chunk. A `string` is UTF-8 encoded (matching the one-shot
   * `compress` convention); a `Uint8Array` is fed verbatim. Returns the
   * bytes produced so far (possibly empty) as a zero-copy view; only the
   * concatenation of every `update()` + `finish()` is a valid stream. Never
   * flushes the encoder (byte-identity invariant).
   */
  update(chunk: string | Uint8Array): Buffer
  /**
   * Flush the encoder and emit the format trailer off the JS thread.
   * Resolves to the tail bytes. Idempotency-guarded: a second call rejects.
   */
  finish(): Promise<Buffer>
}

/** Incremental raw LZMA2 decompressor (dictionary pinned out of band, A10). */
export declare class Lzma2Decompressor {
  /** Create a streaming decompressor and start its decoder worker thread. */
  constructor(options?: Lzma2DecompressorOptions | undefined | null)
  /**
   * Feed one compressed chunk; returns the bytes decoded so far (possibly
   * empty) as a zero-copy view. Deadlock-free under backpressure. The valid
   * output is the concatenation of every `update()` plus the `finish()`
   * tail.
   */
  update(chunk: Uint8Array): Buffer
  /**
   * Signal EOF and resolve to the decoded tail off the JS thread.
   * Idempotency-guarded: a second call rejects cleanly.
   */
  finish(): Promise<Buffer>
}

/** Incremental `.lzma` (LZMA1) compressor: 13-byte header + end marker. */
export declare class LzmaCompressor {
  /**
   * Create a streaming compressor. `options` is optional; an absent or
   * empty object uses [`DEFAULT_PRESET`].
   *
   * The `preset` (and, for LZMA2, `dictSize`) are validated before the
   * native encoder is built, so out-of-range input rejects with an
   * `InvalidArg` error instead of panicking or OOM-ing the process.
   */
  constructor(options?: CompressorOptions | undefined | null)
  /**
   * Feed one chunk. A `string` is UTF-8 encoded (matching the one-shot
   * `compress` convention); a `Uint8Array` is fed verbatim. Returns the
   * bytes produced so far (possibly empty) as a zero-copy view; only the
   * concatenation of every `update()` + `finish()` is a valid stream. Never
   * flushes the encoder (byte-identity invariant).
   */
  update(chunk: string | Uint8Array): Buffer
  /**
   * Flush the encoder and emit the format trailer off the JS thread.
   * Resolves to the tail bytes. Idempotency-guarded: a second call rejects.
   */
  finish(): Promise<Buffer>
}

/** Incremental `.lzma` (LZMA1) decompressor: reads dict/size from the header. */
export declare class LzmaDecompressor {
  /** Create a streaming decompressor and start its decoder worker thread. */
  constructor()
  /**
   * Feed one compressed chunk; returns the bytes decoded so far (possibly
   * empty) as a zero-copy view. Deadlock-free under backpressure. The valid
   * output is the concatenation of every `update()` plus the `finish()`
   * tail.
   */
  update(chunk: Uint8Array): Buffer
  /**
   * Signal EOF and resolve to the decoded tail off the JS thread.
   * Idempotency-guarded: a second call rejects cleanly.
   */
  finish(): Promise<Buffer>
}

/** Incremental `.xz` compressor (empty-input-safe via the shared `XzEncoder`). */
export declare class XzCompressor {
  /**
   * Create a streaming compressor. `options` is optional; an absent or
   * empty object uses [`DEFAULT_PRESET`].
   *
   * The `preset` (and, for LZMA2, `dictSize`) are validated before the
   * native encoder is built, so out-of-range input rejects with an
   * `InvalidArg` error instead of panicking or OOM-ing the process.
   */
  constructor(options?: CompressorOptions | undefined | null)
  /**
   * Feed one chunk. A `string` is UTF-8 encoded (matching the one-shot
   * `compress` convention); a `Uint8Array` is fed verbatim. Returns the
   * bytes produced so far (possibly empty) as a zero-copy view; only the
   * concatenation of every `update()` + `finish()` is a valid stream. Never
   * flushes the encoder (byte-identity invariant).
   */
  update(chunk: string | Uint8Array): Buffer
  /**
   * Flush the encoder and emit the format trailer off the JS thread.
   * Resolves to the tail bytes. Idempotency-guarded: a second call rejects.
   */
  finish(): Promise<Buffer>
}

/** Incremental `.xz` decompressor (supports concatenated `.xz` streams). */
export declare class XzDecompressor {
  /** Create a streaming decompressor and start its decoder worker thread. */
  constructor()
  /**
   * Feed one compressed chunk; returns the bytes decoded so far (possibly
   * empty) as a zero-copy view. Deadlock-free under backpressure. The valid
   * output is the concatenation of every `update()` plus the `finish()`
   * tail.
   */
  update(chunk: Uint8Array): Buffer
  /**
   * Signal EOF and resolve to the decoded tail off the JS thread.
   * Idempotency-guarded: a second call rejects cleanly.
   */
  finish(): Promise<Buffer>
}

/** Options for the LZMA1 and XZ streaming compressors. */
export interface CompressorOptions {
  /** Compression preset `0..=9` (default 6). Higher = smaller output, slower. */
  preset?: number
}

/**
 * Options for the LZMA2 streaming compressor: adds an explicit dictionary size
 * because raw LZMA2 carries none in-band, so encoder and decoder must agree.
 */
export interface Lzma2CompressorOptions {
  /** Compression preset `0..=9` (default 6). */
  preset?: number
  /** Dictionary size in bytes (defaults to 8 MiB, [`backend::LZMA2_DICT_SIZE`]). */
  dictSize?: number
}

/**
 * Options for the LZMA2 streaming decompressor: it must be told the dictionary
 * size the stream was encoded with, because raw LZMA2 carries none in-band.
 */
export interface Lzma2DecompressorOptions {
  /**
   * Dictionary size in bytes (defaults to 8 MiB, [`backend::LZMA2_DICT_SIZE`],
   * which MUST match the encoder's pinned default, A10).
   */
  dictSize?: number
}

export declare namespace lzma {
  export function compress(input: string | Uint8Array, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /**
   * Compress a `ReadableStream<Uint8Array>` into a `.lzma` byte stream. `input`
   * must be a WHATWG `ReadableStream`; wrap a Node `Readable` with
   * `Readable.toWeb()`, or use the `createCompressStream()` factory from the
   * `@napi-rs/lzma/lzma` subpath for a ready-to-pipe Node `Duplex`.
   */
  export function compressStream(input: ReadableStream<Uint8Array>, options?: CompressorOptions | undefined | null): ReadableStream<Buffer>
  export function compressSync(input: string | Uint8Array): Buffer
  export function decompress(input: Uint8Array, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /**
   * Decompress a `.lzma` `ReadableStream<Uint8Array>` into a plaintext stream.
   * `input` must be a WHATWG `ReadableStream`; wrap a Node `Readable` with
   * `Readable.toWeb()`, or use the `createDecompressStream()` factory from the
   * `@napi-rs/lzma/lzma` subpath for a ready-to-pipe Node `Duplex`.
   */
  export function decompressStream(input: ReadableStream<Uint8Array>): ReadableStream<Buffer>
  export function decompressSync(input: Uint8Array): Buffer
}

export declare namespace lzma2 {
  export function compress(input: string | Uint8Array, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /**
   * Compress a `ReadableStream<Uint8Array>` into a raw LZMA2 byte stream.
   * `input` must be a WHATWG `ReadableStream`; wrap a Node `Readable` with
   * `Readable.toWeb()`, or use the `createCompressStream()` factory from the
   * `@napi-rs/lzma/lzma2` subpath for a ready-to-pipe Node `Duplex`.
   */
  export function compressStream(input: ReadableStream<Uint8Array>, options?: Lzma2CompressorOptions | undefined | null): ReadableStream<Buffer>
  export function compressSync(input: string | Uint8Array): Buffer
  export function decompress(input: Uint8Array, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /**
   * Decompress a raw LZMA2 `ReadableStream<Uint8Array>` into a plaintext stream.
   * `input` must be a WHATWG `ReadableStream`; wrap a Node `Readable` with
   * `Readable.toWeb()`, or use the `createDecompressStream()` factory from the
   * `@napi-rs/lzma/lzma2` subpath for a ready-to-pipe Node `Duplex`.
   */
  export function decompressStream(input: ReadableStream<Uint8Array>, options?: Lzma2DecompressorOptions | undefined | null): ReadableStream<Buffer>
  export function decompressSync(input: Uint8Array): Buffer
}

export declare namespace xz {
  export function compress(input: string | Uint8Array, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /**
   * Compress a `ReadableStream<Uint8Array>` into an `.xz` byte stream. `input`
   * must be a WHATWG `ReadableStream`; wrap a Node `Readable` with
   * `Readable.toWeb()`, or use the `createCompressStream()` factory from the
   * `@napi-rs/lzma/xz` subpath for a ready-to-pipe Node `Duplex`.
   */
  export function compressStream(input: ReadableStream<Uint8Array>, options?: CompressorOptions | undefined | null): ReadableStream<Buffer>
  export function compressSync(input: string | Uint8Array): Buffer
  export function decompress(input: Uint8Array, signal?: AbortSignal | undefined | null): Promise<Buffer>
  /**
   * Decompress an `.xz` `ReadableStream<Uint8Array>` into a plaintext stream.
   * `input` must be a WHATWG `ReadableStream`; wrap a Node `Readable` with
   * `Readable.toWeb()`, or use the `createDecompressStream()` factory from the
   * `@napi-rs/lzma/xz` subpath for a ready-to-pipe Node `Duplex`.
   */
  export function decompressStream(input: ReadableStream<Uint8Array>): ReadableStream<Buffer>
  export function decompressSync(input: Uint8Array): Buffer
}
